project:
  type: book

book:
  title: "Chess Notes"
  author: "James Otto"
  date: "11/15/2022"
  chapters:
    - index.qmd
    - part: openings.qmd
      chapters:
        - white.qmd
        - scotch.qmd
        - petrov-defense.qmd
        - black.qmd
        - scandinavian-defense.qmd
  appendices:
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: "css/styles.css"
    number-depth: 2
  pdf:
    documentclass: scrreprt

execute:
  echo: false
  output: false


