<link rel="stylesheet" href="/scripts/chessboard/css/chessboard-1.0.0.css">
      
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2"
        crossorigin="anonymous"></script>

<script src="/scripts/chessboard/js/chessboard-1.0.0.js"></script>

```{r, file='scripts/R/r-setup.R'}
```

```{ojs, file='scripts/js/board-setup.js'}
```

# Fried Liver Attack


```{r}


fried_liver <-
  add_game(
    title = "intro",
    moves = c("e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7"),
    notation = TRUE
  ) |>
  add_game(
    title = "continuation",
    moves = c("e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3", "Nb4"),
    start = 13,
    notation = FALSE
  ) |>
  # add_game(
  #   title = "Endgame",
  #   moves = c("Ka3"),
  #   position = "8/1k6/8/8/8/3Q4/K7/8 w - - 0 1"
  # ) |>
  clean_chess_df()

ojs_define(fried_liver_t = fried_liver)
```

```{ojs}
fried_liver = transpose(fried_liver_t)
```

```{ojs}
fried_liver.map(d => board_setup(fried_liver, d.title))
```

## Introduction

```{r}
#| output: asis
put_board("intro")
```




## Continuing

```{r}
#| output: asis
put_board("continuation")
```

